version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - data:/data/db
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017
    command: mongod --smallfiles --config /etc/mongo/mongod.conf

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_SITE_BASEURL=/mongo
    env_file:
      - envfile
      - secret
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  frontend:
    build:
      context: frontend
    restart: always
    environment:
      - MONGO_HOST=mongodb
    env_file:
      - envfile
      - secret
    depends_on:
      - mongodb
    ports:
      - 80:80
      - 443:443
    volumes:
      - media:/media/
      - ./databases/:/app/databases/
      - ./ssl/:/etc/nginx/ssl/

  ocr_producer:
    build:
      context: python
    restart: always
    env_file:
      - envfile
    volumes:
      - detect:/var/femida_detect
      - media:/media/
    command: run_producer --root=/var/femida_detect --scan-first --host=mongodb
    depends_on:
      - mongodb

  pdf_consumer:
    build:
      context: python
    restart: always
    env_file:
      - envfile
    volumes:
      - detect:/var/femida_detect
      - media:/media/
    command: run_pdf_consumer --root=/var/femida_detect --host=mongodb
    depends_on:
      - ocr_producer

  answers_consumer:
    build:
      context: python
    restart: always
    env_file:
      - envfile
    volumes:
      - media:/media/
      - detect:/var/femida_detect
      - ./model:/model
    command: run_answers_consumer --root=/var/femida_detect --host=mongodb --model-path=/model/model.t7
    depends_on:
      - pdf_consumer

  status_updater:
    build:
      context: python
    restart: always
    env_file:
    - envfile
    volumes:
    - detect:/var/femida_detect
    command: run_status_updater --root=/var/femida_detect --host=mongodb
    depends_on:
    - answers_consumer

volumes:
  data:
  media:
  detect:
