version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - data:/data/db
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
    command: mongod --config /etc/mongo/mongod.conf
    networks:
      - internal
    labels:
      - traefik.enable=false

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_SITE_BASEURL=/mongo
    env_file:
      - envfile
      - secret
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - internal
      - web
    labels:
      - traefik.backend=mongo-express
      - "traefik.frontend.rule=Host:femida.emsch.ru;PathPrefix:/mongo"
      - traefik.docker.network=web

  frontend:
    build:
      context: frontend
    restart: always
    environment:
      - MONGO_HOST=mongodb
    env_file:
      - envfile
      - secret
    depends_on:
      - mongodb
    # ports:
    #  - 80
    #  - 80:80
    #  - 443:443
    volumes:
      - media:/media/
      - ./databases/:/app/databases/
      - ./ssl/:/etc/nginx/ssl/
    networks:
      - internal
      - web
    labels:
      - traefik.backend=femida
      - traefik.frontend.rule=Host:femida.emsch.ru
      - traefik.docker.network=web
      - traefik.port=80

  ocr_producer:
    build:
      context: python
    restart: always
    env_file:
      - envfile
    volumes:
      - detect:/var/femida_detect
      - media:/media/
    command: run_producer --root=/var/femida_detect --scan-first --host=mongodb
    depends_on:
      - mongodb
    networks:
      - internal
    labels:
      - traefik.enable=false

  pdf_consumer:
    build:
      context: python
    restart: always
    env_file:
      - envfile
    volumes:
      - detect:/var/femida_detect
      - media:/media/
    command: run_pdf_consumer --root=/var/femida_detect --host=mongodb
    depends_on:
      - ocr_producer
    networks:
      - internal
    labels:
      - traefik.enable=false

  answers_consumer:
    build:
      context: python
    restart: always
    env_file:
      - envfile
    volumes:
      - media:/media/
      - detect:/var/femida_detect
      - ./model:/model
    command: run_answers_consumer --root=/var/femida_detect --host=mongodb --model-path=/model/model.t7
    depends_on:
      - pdf_consumer
    networks:
      - internal
    labels:
      - traefik.enable=false

  status_updater:
    build:
      context: python
    restart: always
    env_file:
    - envfile
    volumes:
    - detect:/var/femida_detect
    command: run_status_updater --root=/var/femida_detect --host=mongodb
    depends_on:
    - answers_consumer
    networks:
      - internal
    labels:
      - traefik.enable=false

volumes:
  data:
  media:
  detect:
