version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            # TODO test (curl) result
      # `deploy` step: identical to a `run` step, but uses only one container:
      # https://circleci.com/docs/2.0/configuration-reference/#deploy 
      - deploy:
          name: deploy to femida
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              ssh -o StrictHostKeyChecking=no circleci@femida.emsch.ru "cd /femida && git pull && sudo docker-compose up --build -d"
            else
              echo "Not master branch, dry run only"
            fi
